name: CI

on:
  push:
    # branches:
    #   - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: swift-format lint
    runs-on: macOS-15-arm64
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.2"
      - name: swift-format lint
        run: swift format lint --recursive --configuration .swift-format --strict Sources Tests

  test:
    name: Test MacOS
    runs-on: macOS-15-arm64
    timeout-minutes: 30
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.2.app
    strategy:
      matrix:
        destination:
          # - "platform=macOS"
          # - "platform=macOS,variant=Mac Catalyst"
          - "platform=iOS Simulator,name=iPhone 16e"
          - "platform=iOS Simulator,name=iPhone Air"
          # - "platform=tvOS Simulator,name=Apple TV"
          # - "platform=watchOS Simulator,name=Apple Watch Series 10 (42mm)"
          # - "platform=visionOS Simulator,name=Apple Vision Pro"
    steps:
      - uses: actions/checkout@v4
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -skipMacroValidation -scheme DistributedMLS -destination "${{ matrix.destination }}" test | xcbeautify